DATA:
    ROOT: 'path/to/video'
    TRAIN_FILE: 'datasets_splits/ultracls/train.txt'
    VAL_FILE: 'datasets_splits/ultracls/val.txt'
    DATASET: ultracls
    NUM_FRAMES: 16
    NUM_CLASSES: 38
    LABEL_LIST: 'labels/ultracls.csv'
MODEL:
    ARCH: ViT-B/16
    RESUME: "output/train_stage1/ckpt_epoch_29.pth"
TRAIN:
    EPOCHS: 30
    BATCH_SIZE: 4 # BS 512
    ACCUMULATION_STEPS: 16
    LR: 2.2e-05
TEST:
    MULTI_VIEW_INFERENCE: False
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "no_text" # both refers to complete fine-tuning of CLIP (text+image encoders)